version: '3.8'

services:
  mitmproxy:
    build: ./mitmproxy
    ports:
      - "8081:8081"
    networks:
      - youtube-network
    restart: unless-stopped

  websocket-server:
    build: ./websocket-server
    ports:
      - "8080:8080"
    networks:
      - youtube-network
    depends_on:
      - mitmproxy
    restart: unless-stopped

networks:
  youtube-network:
    driver: bridge